#ifndef OPENPNP_BOARD_PINS_H
#define OPENPNP_BOARD_PINS_H

#include "stm32g4xx_hal.h"

/*
 * Provisional LQFP48 pin contract v1. Do not flash the normal-mode image until
 * these signals have been checked against the actual schematic.
 */
#define BOARD_PIN_CONTRACT_VERSION 1UL

#define BOARD_FDCAN_RX_PORT GPIOA
#define BOARD_FDCAN_RX_PIN GPIO_PIN_11
#define BOARD_FDCAN_TX_PORT GPIOA
#define BOARD_FDCAN_TX_PIN GPIO_PIN_12
#define BOARD_FDCAN_GPIO_AF GPIO_AF9_FDCAN1
#define BOARD_FDCAN_STANDBY_PORT GPIOB
#define BOARD_FDCAN_STANDBY_PIN GPIO_PIN_2

#define BOARD_AXIS0_STEP_PORT GPIOA
#define BOARD_AXIS0_STEP_PIN GPIO_PIN_8
#define BOARD_AXIS0_DIRECTION_PORT GPIOB
#define BOARD_AXIS0_DIRECTION_PIN GPIO_PIN_0
#define BOARD_AXIS0_ENABLE_PORT GPIOB
#define BOARD_AXIS0_ENABLE_PIN GPIO_PIN_1

#define BOARD_AXIS0_ENABLE_ACTIVE_STATE GPIO_PIN_RESET
#define BOARD_AXIS0_ENABLE_INACTIVE_STATE GPIO_PIN_SET

#endif
